Documentation:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/OptionalArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Lint/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block

Lint/DefEndAlignment:
  EnforcedStyleAlignWith: start_of_line

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4
